# -*- coding: utf-8 -*-
"""explainableai.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yd-EkQXUOBTGv27WQtCjbu8tj8v97fAj
"""

# Install required library first (if not installed)
# pip install scikit-learn

from sklearn.tree import DecisionTreeClassifier, export_text
import numpy as np

# Sample Training Data
# Features: [Attendance %, Study Hours per day, Internal Marks]
X = np.array([
    [90, 4, 85],
    [80, 3, 75],
    [60, 2, 50],
    [50, 1, 40],
    [95, 5, 92],
    [70, 2, 65],
    [85, 3, 78],
    [55, 1, 45]
])

# Labels
# 0 = At Risk
# 1 = Pass
# 2 = Distinction
y = np.array([2, 1, 0, 0, 2, 1, 1, 0])

# Create Decision Tree Model
model = DecisionTreeClassifier()
model.fit(X, y)

# Taking User Input
attendance = float(input("Enter Attendance (%): "))
study_hours = float(input("Enter Study Hours per day: "))
marks = float(input("Enter Internal Marks: "))

# Prediction
prediction = model.predict([[attendance, study_hours, marks]])

result = {
    0: "At Risk",
    1: "Pass",
    2: "Distinction"
}

print("\nPredicted Result:", result[prediction[0]])

# Show Explainable Rules
print("\nDecision Rules Used by Model:\n")
tree_rules = export_text(model, feature_names=["Attendance", "Study Hours", "Marks"])
print(tree_rules)